export const data = [
    {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/1.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': false,
        'instock':false,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/7.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': false,
        'instock': false,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/10.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': false,
        'instock': false,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/3.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': false,
        'instock': false,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/6.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': false,
        'instock': false,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/11.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': false,
        'instock': false,
    }, {
        'name': 'Cycle',
        'price': 10000,
        'image': './images/10.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': true,
        'instock': false,
    }, {
        'name': 'Cycle',
        'price': 8888,
        'image': './images/12.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': false,
        'instock': true,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/10.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': false,
        'instock': false,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/9.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': false,
        'instock': false,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/2.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': false,
        'instock': false,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/11.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': true,
        'instock': true,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/1.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': false,
        'instock': false,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/10.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': false,
        'instock': false,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/12.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': true,
        'instock': true,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/2.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery':false,
        'instock': true,
    }, {
        'name': 'Cycle',
        'price': 20000,
        'image': './images/3.png',
        'description': 'A simplified way to generate massive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing.',
        'fastdelivery': false,
        'instock': false,
    },
]